version: '3'

services:
  database:
    image: 'postgres:10.4-alpine'
    environment:
      POSTGRES_DB: 'xtrd_api'
      POSTGRES_USER: 'xtrd_api'
      POSTGRES_PASSWORD: 'xtrd_api'
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
