# Generated by Django 2.1 on 2018-08-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('price_usd', models.DecimalField(decimal_places=5, max_digits=1000, verbose_name='USD')),
                ('price_eth', models.DecimalField(decimal_places=18, max_digits=1000, verbose_name='ETH')),
                ('volume', models.DecimalField(decimal_places=18, max_digits=1000, verbose_name='Volume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
